openapi: 3.0.0
info:
  title: API de Processos
  description: API para gerenciar processos.
  version: 1.0.0

paths:
  /api/process-manager:
    get:
      summary: Lista todos os processos
      tags:
        - Processos
      responses:
        '200':
          description: Lista de processos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID único do processo
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID do usuário
                        name:
                          type: string
                          description: Nome do usuário
                    fileName:
                      type: string
                      description: Nome do arquivo original
                    createdAt:
                      type: string
                      format: date-time
                      description: Data e hora de criação do processo
                    status:
                      type: string
                      description: Status atual do processo (ex: 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DOWNLOADED')
                    zipKey:
                      type: string
                      description: Chave do arquivo ZIP processado (disponível quando status é COMPLETED, removida após DOWNLOADED)
  
  /api/process-manager/upload:
    post:
      summary: Upload de arquivo
      tags:
        - Processos
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: ID do usuário que está fazendo o upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: Arquivo de vídeo para upload
      responses:
        '200':
          description: Upload realizado com sucesso

  /api/process-manager/{processId}/download:
    get:
      summary: Download do arquivo ZIP processado
      tags:
        - Processos
      parameters:
        - in: path
          name: processId
          required: true
          schema:
            type: string
          description: ID do processo
      responses:
        '200':
          description: Download do arquivo ZIP realizado com sucesso
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Erro na requisição (processo não encontrado, sem ZIP disponível, etc.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string