openapi: 3.0.0
info:
  title: API de Processos
  description: |
    API para gerenciar processos.
    
    **Nota importante para downloads:** O endpoint de download pode levar alguns minutos para processar arquivos grandes. O timeout está configurado para 5 minutos.
  version: 1.0.0

servers:
  - url: /
    description: Servidor local
    variables:
      timeout:
        default: "300000"
        description: Timeout em millisegundos (5 minutos)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Token JWT no formato: Bearer <token>'
  
  responses:
    UnauthorizedError:
      description: Token de acesso ausente ou inválido
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Token não fornecido ou inválido"
    
    ForbiddenError:
      description: Acesso negado - token válido mas sem permissões suficientes
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Acesso negado"

security:
  - bearerAuth: []

paths:
  /api/process-manager:
    get:
      summary: Lista processos do usuário logado
      description: Retorna todos os processos que pertencem ao usuário autenticado
      tags:
        - Processos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de processos do usuário retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID único do processo
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID do usuário
                        name:
                          type: string
                          description: Nome do usuário
                    fileName:
                      type: string
                      description: Nome do arquivo original
                    createdAt:
                      type: string
                      format: date-time
                      description: Data e hora de criação do processo
                    status:
                      type: string
                      description: Status atual do processo (ex: 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DOWNLOADED')
                    zipKey:
                      type: string
                      description: Chave do arquivo ZIP processado (disponível quando status é COMPLETED, removida após DOWNLOADED)
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  
  /api/process-manager/upload:
    post:
      summary: Upload de arquivo
      tags:
        - Processos
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: ID do usuário que está fazendo o upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: Arquivo de vídeo para upload
      responses:
        '200':
          description: Upload realizado com sucesso
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/process-manager/{processId}/download:
    get:
      summary: Download do arquivo ZIP processado
      description: |
        Realiza o download do arquivo ZIP processado. 
        
        **⚠️ Importante:**
        - Este endpoint pode levar alguns minutos para arquivos grandes
        - O processo será marcado como DOWNLOADED após o download
        - O arquivo será removido do S3 após o download bem-sucedido
        - Timeout configurado para 5 minutos
        
        **Pré-requisitos:**
        - Processo deve estar no status COMPLETED
        - Arquivo ZIP deve estar disponível no S3
      tags:
        - Processos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: processId
          required: true
          schema:
            type: string
          description: ID do processo
      responses:
        '200':
          description: Download do arquivo ZIP realizado com sucesso
          headers:
            Content-Type:
              schema:
                type: string
                example: application/zip
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="processo-result.zip"
            Content-Length:
              schema:
                type: integer
                description: Tamanho do arquivo em bytes
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Erro na requisição (processo não encontrado, sem ZIP disponível, etc.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/process-manager:
    delete:
      summary: Deletar processos
      tags:
        - Processos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                processIds:
                  type: array
                  items:
                    type: string
                  description: Array de IDs dos processos a serem deletados
              example:
                processIds: ["process-id-1", "process-id-2"]
      responses:
        '200':
          description: Exclusão concluída com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  deletedCount:
                    type: integer
                    description: Número de processos deletados
                  skippedCount:
                    type: integer
                    description: Número de processos pulados (em andamento)
                  errors:
                    type: array
                    items:
                      type: string
                    description: Lista de erros ocorridos
        '207':
          description: Exclusão parcialmente concluída (com alguns erros)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  deletedCount:
                    type: integer
                  skippedCount:
                    type: integer
                  errors:
                    type: array
                    items:
                      type: string
        '400':
          description: Erro na requisição
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'