apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-fiap-process-manager-application-ms
  labels:
    app: soat-fiap-process-manager-application-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat-fiap-process-manager-application-ms
  template:
    metadata:
      labels:
        app: soat-fiap-process-manager-application-ms
    spec:
      containers:
        - name: soat-fiap-process-manager-application-ms
          image: 608645417480.dkr.ecr.us-east-1.amazonaws.com/soat-fiap-process-manager-application-ms:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-process-manager-application-ms-configmap
                  key: AWS_REGION
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-process-manager-application-ms-configmap
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-process-manager-application-ms-configmap
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-process-manager-application-ms-configmap
                  key: LOG_LEVEL
            - name: USERS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: soat-fiap-process-manager-application-ms-configmap
                  key: USERS_BASE_URL
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1000m"
